export type getDonationTypes = {
  fromDate?: string;
  toDate?: string;
  limit?: number;
  page?: number;
  _id?: string;
  devotee?: string;
  phone?: string;
  address?: string;
  donation?: string;
  performance_date?: string;
  in_behalf_of?: string;
  amount?: number;
  booked_on?: string;
  occasion?: string;
  email?: string;
  gothram?: string;
  pincode?: string;
  state?: string;
  country?: string;
  paksham?: string;
  telugu_month?: string;
  sub_tidi?: string;
  createdAt?: string;
  updatedAt?: string;
};
