export interface PoojaDataTypes {
  poojaName: string;
  price: number;
}
export const poojasDummyData: Array<PoojaDataTypes> = [
  { poojaName: "Veda Ashirvachanam", price: 1116 },
  { poojaName: "Archana / Ashirvachanam", price: 500 },
  { poojaName: "Sri Lakshmi Narayana Homam", price: 400 },
  {
    poojaName: "Sri Swami Vari Kalyanam Jeshta Sudda Ekadashi Kalyanam",
    price: 1000,
  },
  { poojaName: "Sahasranamam", price: 150 },
  { poojaName: "Vivaha Kanuka", price: 2000 },
  { poojaName: "Dwichakra Vahana Pooja", price: 100 },
  { poojaName: "Ambothu Achhu Veyutaku", price: 500 },
  { poojaName: "Naalugu Chakrala Vahana Pooja", price: 200 },
  { poojaName: "Laksha Tulasi Pooja", price: 250 },
  { poojaName: "Laksha Chamanti Pooja Andal Ammavaru Mukkoti", price: 250 },
  { poojaName: "Vijaya Dashami Rojuna Laksha Kumkuma Pooja", price: 250 },
  { poojaName: "Abhishekam Sri Swami Variki", price: 100 },
  { poojaName: "Annaprasana", price: 300 },
  { poojaName: "Vivaha Kanuka (Shed 5000)", price: 5000 },
  { poojaName: "Upanayanamu", price: 500 },
  { poojaName: "Aksharabhyasam", price: 300 },
  { poojaName: "Namakaranam", price: 300 },
  { poojaName: "Masa Kalyanam (Shravana Nakshatram)", price: 1000 },
  { poojaName: "Laksha Kumkuma Pooja Vijayadashami", price: 250 },
  { poojaName: "Suprabhata Seva", price: 500 },
  { poojaName: "Shighra Darshanam", price: 100 },
  { poojaName: "Keshakhandana Shaala", price: 40 },
  { poojaName: "Shaashvata Laksha Kumkuma Pooja Vijayadashami", price: 2000 },
  {
    poojaName: "Shaashvata Laksha Tulasi Pooja Kartika Shuddha Ekadashi",
    price: 2000,
  },
  { poojaName: "Shaashvata Nitya Kalyanam", price: 7000 },
  { poojaName: "Shaashvata Usha Kalarachana", price: 2000 },
  { poojaName: "Shaashvata Ashtottaram", price: 2000 },
  { poojaName: "Shaashvata Panchamrutabhishekam", price: 5000 },
  {
    poojaName: "Shaashvata Laksha Chamanti Pooja Mukkoti Ekadashi",
    price: 2000,
  },
  { poojaName: "Shaashvata Sahasranamam", price: 4000 },
];
export const poojasDummyDataTelugu: Array<PoojaDataTypes> = [
  { poojaName: "వేదాశీర్వచనం", price: 1116 },
  { poojaName: "అర్చన / ఆశీర్వచనం", price: 500 },
  { poojaName: "శ్రీలక్ష్మి నారాయణ హోమం", price: 400 },
  {
    poojaName: "శ్రీ స్వామి వారి కల్యాణం జేష్ట సుద్ద ఏకాదశి కళ్యాణం",
    price: 1000,
  },
  { poojaName: "సహస్త్రనామం", price: 150 },
  { poojaName: "వివాహ కానుక", price: 2000 },
  { poojaName: "ద్విచక్ర వాహన పూజ", price: 100 },
  { poojaName: "ఆంబోతు అచ్చువేయుటకు", price: 500 },
  { poojaName: "నాలుగు చక్రాల వాహన పూజ", price: 200 },
  { poojaName: "లక్ష తులసి పూజ", price: 250 },
  { poojaName: "లక్ష చామంతి పూజ ఆండాళ్ అమ్మవారు ముక్కోటి", price: 250 },
  { poojaName: "విజయదశమి రోజున లక్ష కుంకుమ పూజ", price: 250 },
  { poojaName: "అభిషేకం శ్రీ స్వామి వారికీ", price: 100 },
  { poojaName: "అన్నప్రాసన", price: 300 },
  { poojaName: "వివాహ కానుక ( షెడ్ 5000)", price: 5000 },
  { poojaName: "ఉపనయనము", price: 500 },
  { poojaName: "అక్షరాభ్యాసం", price: 300 },
  { poojaName: "నామకరణం", price: 300 },
  { poojaName: "మాస కళ్యాణం(శ్రావణ నక్షిత్రం)", price: 1000 },
  { poojaName: "లక్ష కుంకుమ పూజ విజయదశమి", price: 250 },
  { poojaName: "సుప్రబాత సేవ", price: 500 },
  { poojaName: "శీఘ్ర దర్శనం", price: 100 },
  { poojaName: "కేశఖండన శాల", price: 40 },
  { poojaName: "శాశ్వత లక్ష కుంకుమ పూజా విజయదశమి", price: 2000 },
  { poojaName: "శాశ్వత లక్ష తులసీ పూజ కార్తీకశుద్ధ ఏకాదశి", price: 2000 },
  { poojaName: "శాశ్వత నిత్య కల్యాణం", price: 7000 },
  { poojaName: "శాశ్వత ఉష కాలార్చన", price: 2000 },
  { poojaName: "శాశ్వత అష్టోత్తరం", price: 2000 },
  { poojaName: "శాశ్వత పంచామృతాభిషేకం", price: 5000 },
  { poojaName: "శాశ్వత లక్ష చామంతి పూజ ముక్కోటి ఏకాదశి", price: 2000 },
  { poojaName: "శాశ్వత సహస్రనామం", price: 4000 },
];
